name: Build pandas
description: Rebuilds the C extensions and installs pandas
runs:
  using: composite
  steps:

    - name: Environment Detail
      run: |
        micromamba info
        micromamba list
      shell: bash -el {0}

    - name: Build Pandas
      run: |
        # TODO: uncomment this after meson/meson-python bugs patched
        #python -m pip install . -v
        install_dir=$(python -c "import sysconfig; print(sysconfig.get_path('platlib'))")
        meson setup builddir
        cd builddir
        meson configure -Dprefix=$install_dir
        meson compile
        meson install
      shell: bash -el {0}
#      env:
#        # Cannot use parallel compilation on Windows, see https://github.com/pandas-dev/pandas/issues/30873
#        # GH 47305: Parallel build causes flaky ImportError: /home/runner/work/pandas/pandas/pandas/_libs/tslibs/timestamps.cpython-38-x86_64-linux-gnu.so: undefined symbol: pandas_datetime_to_datetimestruct
#        N_JOBS: 1
#        #N_JOBS: ${{ runner.os == 'Windows' && 1 || 2 }}
